### PR TITLE
Call fsync/fdatasync on File::close

### PR DESCRIPTION
**Pull request by vrusinov**
Improves durability in the event of sudden crash - fclose() does not
guarantee that data is actually flushed to disk. This is first step in
durability improvement plan discussed in
https://github.com/GothenburgBitFactory/taskwarrior/issues/152.

The main user - TaskWarriror's TDB2 sequentlally calls close() at the end of
each command on four files. If the files were not modified, fsync() should be
close to no-op - we'll pay small price to syscall/context switch.

However if the files are dirty we will pay some performance penalty.
Most of the time fsync() will wait for 2 blocks to be persisted while
fdatasync() will usually require just one. On HDD this could add about
10ms per block, so on 4 dirty files in non-Linux system this could
add up to 80ms of latency to each modifying command. On Linux on SSD
this could be under 4ms (assuming SSD is in good state and does not trigger gc
on every write).

This seems small enough price to pay.

---

This PR depends on #42. It still compiles without C++17 flag but emits a warning.

### CODE REVIEW

**Comment by tbabej** [comment]
Ugh, Github UI failed me here with the resolve conflicts button. I rebased and merged the MR manually. Thanks for the implementation!

**Comment by tbabej** [comment]
Looks like we should expand the test suite here to include a larger set of OS setups. The Taskwarrior tests have failed due to the following build problem on Mac OS-X:

```
[ 14%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/FS.cpp.o
/Users/runner/work/taskwarrior/taskwarrior/src/libshared/src/FS.cpp:497:19: error: use of undeclared identifier '__linux'
    if constexpr (__linux) {
                  ^
/Users/runner/work/taskwarrior/taskwarrior/src/libshared/src/FS.cpp:498:11: error: use of undeclared identifier 'fdatasync'
      if (fdatasync (fileno (_fh)))
          ^
2 errors generated.
make[2]: *** [src/CMakeFiles/libshared.dir/libshared/src/FS.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/libshared.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tbabej** [comment]
Looks like on Mac OS-X we might want to call `fcntl(fd, F_FULLFSYNC, 0)` instead? But this section of the code would still need to be put into `#if defined` guard, because the `fdatasync` is not implemented on OS X.

**Comment by vrusinov** [comment]
Ugh, sorry for that - I wasn't aware that OS-X does not even define fdatasync. I'll look into this shortly.

**Comment by tbabej** [comment]
No worries, I fell for the same mistake at first. I'll look into expanding the CI capabilties on this repo to include OS-X as one of the tested platforms.

**Comment by vrusinov** [comment]
> I'll look into expanding the CI capabilties on this repo to include OS-X as one of the tested platforms.

I did the quick version of it in https://github.com/vrusinov/libshared/commit/051170eff5c70a9a10bf90d499367c2d5af4d129
There is only a small number of different runners available in github CI so it may require docker-based approach like in TaskWarrior.

**Pull request closed without merging**
