### PR TITLE
Add 24bit color support

### LINKED ISSUE #3: Support true color
The Color class should support true color, 8 bits per channel.

### PR DESCRIPTION
**Pull request by xs5871**
Here's a suggestion for 24-bit color ("truecolor") support:
* Keep the original structure of stuffing all color information into a single integer.
* But use a 64 bit int instead.
* If 24-bit color: store the background color in the upper half.

resolves #3

### CODE REVIEW

**Comment by lauft** [comment]
@xs5871 Thanks for the contribution, but there are some failing tests that need to be investigated. 
From the test logs:
```
not ok 1038 - 0x0a1b2c               -> ^[[38;2;10;27;44m
# expected: 'foo'
#      got: '[38;2;10;27;44mmfoo'
not ok 1039 - 0x0a1b2c on color127   -> ^[[38;2;10;27;44m^[[48;2;126;0;126m
# expected: 'foo'
#      got: '[38;2;10;27;44m;mfoo'
not ok 1040 - red on 0x0a1b2c        -> ^[[38;2;128;0;0m^[[38;2;10;27;44m
# expected: 'foo'
#      got: '[38;2;128;0;0m;mfoo'
not ok 1041 - bold on 0x0a1b2c       -> ^[[38;2;255;0;0m^[[38;2;10;27;44m
# expected: 'foo'
#      got: '[38;2;128;0;0m;mfoo'
not ok 1042 - 0x0a1b2c on bright red -> ^[[38;2;10;27;44m^[[48;2;255;0;0m
# expected: 'foo'
#      got: '[38;2;10;27;44m;mfoo'
not ok 1043 - 0x0101010 on grey0     -> ^[[38;2;1;1;1m^[[48;2;10;10;10m
# expected: 'foo'
#      got: '[38;2;1;1;1m;mfoo'
not ok 1044 - 0x101010 on grey0      -> ^[[38;2;16;16;16m^[[48;2;240;240;240m
# expected: 'foo'
#      got: '[38;2;16;16;16m;mfoo'
```

**Comment by xs5871** [comment]
Got confused by the regex warnings. Those didn't show up when I originallly wrote this.

**Comment by Rahlir** [comment]
Uuuh, that's neat. I would just point out that if this gets merged it would be very useful to also update the documentation of the main project. Plus we need to update the documentation regarding colors anyway now that #85 was merged...

**Comment by lauft** [comment]
@xs5871 I spotted some minor issues on a second pass of your PR:
* Update the number of unit tests by 8 in line 34 of `color.t.cpp`
* The last test should have the description `0x101010 on grey23` instead of `0x101010 on grey0`

**Comment by xs5871** [comment]
I also moved the new tests up a bit. For some reason they were in the middle of semantically contiguous section.

**Review by lauft — APPROVED** [review]

**Pull request merged**
