### PR TITLE
Add vscode directory to gitignore

### PR DESCRIPTION
**Pull request by vrusinov**

### CODE REVIEW

**Comment by lauft** [comment]
This is a very personal opinion, but I would prefer to have such entries rather in the private `.git/info/exclude` file... 🤔

**Comment by tbabej** [comment]
@lauft I didn't know that existed, great tip!

**Comment by vrusinov** [comment]
Me neither. Should I replace this PR with update to the docs?

**Comment by smemsh** [comment]
if you want them ignored in all your repos globally, you could add it to a `~/.config/git/ignore` file also (or a different `core.excludesFile` referenced in your `.gitconfig`)

> Should I replace this PR with update to the docs

well, it's right in `gitignore` man page toplevel description, though...

**Comment by vrusinov** [comment]
> > Should I replace this PR with update to the docs
> 
> well, it's right in `gitignore` man page toplevel description, though...

I meant something like a comment - see updated diff.

**Comment by lauft** [comment]
Thanks! 👍🏻

**Comment by smemsh** [comment]
> > well, it's right in `gitignore` man page toplevel description, though...
> 
> I meant something like a comment

right, I just think they are tautological comments.  oh well :-)

**Pull request merged**
